spring:
 application:
  name: eurekaserver
 config:
  import: "optional:configserver:http://localhost:8071/"
server:
  port: 8092
  
eureka:
 client:
    register-with-eureka: false
    fetch-registry: false
