server:
  port: 8080
spring:
  application:
    name: "account"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
   
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    
management:
  endpoints:
    web:
      exposure:
        include: "*" 
        
logging:
  level:
    org:
     springframework: 
     web:
      servlet: 
       resource: ERROR
